---
swagger: "2.0"
info:
  description: "uaek api"
  version: "0.0.1"
  title: "uaek api"
host: "127.0.0.1:18080"
basePath: "/api/"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /whoami:
    get:
      responses:
        200:
          description: "cluster info"
          schema:
            properties:
              username:
                type: string
              registered:
                type: boolean


  /cluster:
    get:
      summary: "get cluster list"
      responses:
        200:
          description: "a list of cluster"
          schema:
            type: array
            items:
              properties:
                name:
                  type: string
        500:
          description: "An unexpected error occured."
  /cluster/{cluster_name}:
    get:
      summary: "get cluster by name"
      parameters:
        - name: cluster_name
          in: path
          required: true
          type: string
      responses:
        200:
          description: "cluster info"
          schema:
            properties:
              name:
                type: string
              addr:
                type: string
              cert:
                type: string
        400:
          description: cluster not found
  
  /user:
    get:
      responses:
        200:
          description: "a list of user name" 
          schema:
            type: array
            items:
              properties:
                name:
                  type: string
        500:
          description: "An unexpected error occured."
    post:
      summary: creates a user
      parameters:
        - name: user
          in: body
          description: the user to create.
          schema:
            required:
              - name
            properties:
              name:
                type: string
      responses:
        204:
          description: user succesfully created.
        400:
          description: user couldn't have been created.
              
  /user/{username}:
    get:
      parameters:
        - name: username
          in: path
          required: true
          type: string
      responses:
        200:
          description: user info
          schema:
            properties:
              name:
                type: string
              project:
                type: array
                items:
                  properties:
                    name:
                      type: string
              role:
                type: array
                items:
                  properties:
                    name:
                      type: string
              project_quota:
                type: string

  /project:
    get:
      responses:
        200:
          description: project info
          schema:
            type: array
            items:
              properties:
                name:
                  type: string
        500:
          description: "An unexpected error occured."
    post:
      summary: creates a project
      parameters:
        - name: project
          in: body
          description: the project to create.
          schema:
            required:
              - name
            properties:
              name:
                type: string
      responses:
        204:
          description: project succesfully created.
        400:
          description: project couldn't have been created.
          
  /project/{prjname}/user:
    get:
      description: get project user
      parameters:
        - name: prjname
          in: path
          required: true
          type: string
      responses:
        200:
          description: user info
          schema:
            properties:
              name:
                type: string
                
  /project/{prjname}/user/{username}:
    post:
      summary: add a user
      parameters:
        - name: prjname
          in: path
          required: true
          type: string
        - name: username
          in: path
          required: true
          type: string
      responses:
        204:
          description: user succesfully created.
        400:
          description: user couldn't have been created.
          
  
  /project/{prjname}/cluster:
    get:
      description: get bound cluster
      parameters:
        - name: prjname
          in: path
          required: true
          type: string
      responses:
        200:
          description: cluster info
          schema:
            properties:
              name:
                type: string
    
  /project/{prjname}/cluster/{clustername}:
    post:
      summary: creates a project
      parameters:
        - name: prjname
          in: path
          description: the project to bind.
          required: true
          type: string
        - name: clustername
          in: path
          description: the cluster to bind.
          required: true
          type: string
      responses:
        204:
          description: project and cluster succesfully bound.
        400:
          description: project and cluster could not be bound.
          
  /cluster/{cluster_name}/account:
    parameters:
      - name: cluster_name
        in: path
        required: true
        type: string
    get:
      responses:
        200:
          description: get account info
          schema:
            properties:
              cluster:
                type: string
              user:
                type: string
              token:
                type: string
        400:
          description: not found
    post:
      responses:
        204:
          description: account succesfully created.
        400:
          description: not found
          
          
  /cluster/{cluster_name}/namespace:
    parameters:
      - name: cluster_name
        in: path
        required: true
        type: string
    get:
      responses:
        200:
          description: get cluster namesapce
          schema:
            type: array
            items:
              properties:
                name:
                  type: string
        400:
          description: not found
          
          
  /cluster/{cluster_name}/permit/{ns_name}:
    parameters:
      - name: cluster_name
        in: path
        required: true
        type: string
      - name: ns_name
        in: path
        required: true
        type: string
    post:
      responses:
        204:
          description: permit succesfully created.
        400:
          description: not found
          
          
  /cluster/{cluster_name}/permit/:
    parameters:
      - name: cluster_name
        in: path
        required: true
        type: string
    get:
      responses:
        200:
          description: all permitted namespace in the cluster
          schema:
            type: array
            items:
              properties:
                namespace:
                  type: string
        400:
          description: not found
    
    